### PR TITLE
Research best way to package and ship php cs fixer rules

### LINKED ISSUE #1: Research best way to package and ship php-cs-fixer rules
Ideally, I'd like to be able to require a package with composer and be able to do something like `@dflydev` as a ruleset. However, my little research shows it may be impossible.

The best example I've seen so far is here:

* https://github.com/mollie/php-coding-standards

I'd like to know how you can use Mollie's coding standards using this format:

```php
$rules = [
    '@PER' => true,
    '@Symfony' => true,
    // ...
];


return (new Config())
    ->setFinder($finder)
    ->setRules($rules) // ...
    ->setRiskyAllowed(true)
    ->setUsingCache(true);
```

 * Can we include an array in addition to a class name for `setRules`?
 * Can we call `setRules` multiple times?
 * We'd want to ensure we can easily override the rules inside this package... and that means the order is important.

----

We should use the following as the basis for the ruleset:

```php
<?php

declare(strict_types=1);

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

$rules = [
    '@PER' => true,
    '@Symfony' => true,

    'declare_strict_types' => true,

    // Override @Symfony

    'phpdoc_align' => [
        'align' => 'left',
        'tags' => [
            'method',
            'param',
            'property',
            'property-read',
            'property-write',
            'return',
            'throws',
            'type',
            'var',
        ],
    ],

    'phpdoc_separation' => [
        'groups' => [
            // Defaults
            ['deprecated', 'link', 'see', 'since'],
            ['author', 'copyright', 'license'],
            ['category', 'package', 'subpackage'],
            ['property', 'property-read', 'property-write'],

            // Overrides
            ['template', 'template-covariant', 'template-uses'],

            ['uses'],

            ['phpstan-*'], // This is not available... yet.

            ['phpstan-param', 'phpstan-return'],
        ],
    ],

    'global_namespace_import' => [
        'import_classes' => null,
        'import_constants' => true,
        'import_functions' => true,
    ],
    'no_empty_comment' => false,
    'php_unit_method_casing' => ['case' => 'snake_case'],
    'single_line_throw' => false,
    'yoda_style' => false,

    'phpdoc_to_comment' => [
        'ignored_tags' => [
            'array',
            'var',
            'phpstan-var',
        ],
    ],
];
```

### LINKED ISSUE #2: Add composer.json
The package name should be `dflydev/php-coding-standards`.

### PR DESCRIPTION
**Pull request by zaherg**
This PR should closes #1 and resolve #2 once it is merged
---

### Usage

```bash
composer require dflydev/php-coding-standards
```

Create a new `.php-cs-fixer.dist.php` file and within it add the following:

```php
use Ergebnis\PhpCsFixer\Config;

$config = Config\Factory::fromRuleSet(new Dflydev\PhpCsFixer\Config\RuleSet\Dflydev());

$config->getFinder()->in(__DIR__);
$config->setCacheFile(__DIR__ . '/.php-cs-fixer.cache');

return $config;
```

### Configuration with override rules

💡 Optionally override rules from a rule set by passing in an array of rules to be merged in:

```php
use Ergebnis\PhpCsFixer\Config;

$config = Config\Factory::fromRuleSet(new Dflydev\PhpCsFixer\Config\RuleSet\Dflydev(), [
    'mb_str_functions' => false,
    'strict_comparison' => false,
    '@PER' => true,
    '@Symfony' => true,
]);

$config->getFinder()->in(__DIR__);
$config->setCacheFile(__DIR__ . '/.php-cs-fixer.cache');

return $config;
```

### CODE REVIEW

**Comment by zaherg** [comment]
Another option, we can use the config templates mentioned here https://localheinz.com/articles/2023/04/10/introducing-php-cs-fixer-into-legacy-projects/

**Review by simensen — CHANGES_REQUESTED** [review]
The only thing I'd change is probably to use `DflydevConfig` instead of `DflyConfig` for the class name.

----

This looks like a good start. I like this other style (see the image below), but this should work fine for now. I'm not sure I care that much. :) I only found this because I was clicking around some of what you put in this PR so far!

image

https://localheinz.com/articles/2023/03/10/sharing-configurations-for-php-cs-fixer-across-projects/

**Comment by zaherg** [comment]
basically using this template https://github.com/ergebnis/php-cs-fixer-config-template

**Comment by simensen** [comment]
> basically using this template https://github.com/ergebnis/php-cs-fixer-config-template

Yeah, more or less.

----

Weird, I could sear I responded to this yesterday, but it looks like I either didn't at all or I failed to click comment?!

**Comment by simensen** [comment]
> basically using this template https://github.com/ergebnis/php-cs-fixer-config-template

Yes, basically.

----

🙄 Here it is...

image

**Comment by zaherg** [comment]
I'll see what can I do

**Comment by zaherg** [comment]
I have updated the code so that we can implement https://github.com/ergebnis/php-cs-fixer-config package and have our own custom `ruleset`

at the same time, I added a working formatter for us that we can use 
https://github.com/dflydev/dflydev-php-coding-standards/blob/129b0273b85afb7e66c609107150e08ef17f6292/.php-cs-fixer.dist.php

**Review by simensen — APPROVED** [review]
This looks good for now! Let's start using it and see if we run into any issues. :)

**Pull request merged**
